### ISSUE TITLE
Tree generator

### ISSUE THREAD

**Issue by cdupont** [luqui/control-monad-omega#5]
Hello,
I've been using your library with success so far. Thanks!
I use it to generate all possible trees.
Here is something I noticed:

```
module Main where

import Control.Monad.Omega
import Control.Applicative

main = putStrLn $ show $ take 5 $ runOmega allTrees

data Tree = Node Int Tree
          | Leaf
          deriving (Eq, Ord, Show)

allTrees :: Omega Tree
allTrees =  pure Leaf 
        <|> (Node 1 <$> allTrees)
        <|> (Node 2 <$> allTrees)
        <|> (Node 3 <$> allTrees)
        <|> (Node 4 <$> allTrees)
```
Running it:
```
$ stack script test2.hs  --resolver lts-18.12
[Leaf,Node 1 Leaf,Node 4 Leaf,Node 3 Leaf,Node 4 (Node 1 Leaf)]
```
It's surprising that the search is not "breadth first": there is no `Node 2 Leaf`before digging down.
The order of the nodes is not respected, too.
Did I miss something?
Thanks

**Comment by cdupont** [comment]
I noticed this comment:
```
Warning: Omega is only a monad when the results of runOmega are interpreted as a set; that is, a valid transformation according to the monad laws may change the order of the results. However, the same set of results will always be reachable. If you are using this as a monad, I recommend that you use the newer weighted-search package instead (it's also faster).
```
Is it the explanation?
Which weighted-search package are you referring to?

**Comment by luqui** [comment]
Well notice that, as least, I can't continue the pattern `[Leaf, Node 1 Leaf, Node 2 Leaf, Node 3 Leaf ...]`, because then

    pure Leaf <|> asum [ Node n <$> allTrees | n <- [1..] ]

would never reach `Node 1 (Node 1 Leaf)`, and the whole point of this monad is to squash everything to order type omega.

However it is suspect that `Node 4 Leaf` appears before `Node 3 Leaf`, and that `Node 2 Leaf` doesn't appear yet, and I don't have an explanation for that.  I would expect something more like

    [Leaf, Node 1 Leaf, Node 2 Leaf, Node 1 (Node 1 Leaf), Node 3 Leaf, Node 1 (Node 1 (Node 1 Leaf)), Node 2 (Node 1 Leaf) ...]

that is, that `Node 1 t` always appears before `Node 2 t` for the same t, and we descend breadthwise and depthwise simultaneously.  I'll have to review the code to see what's up here, and I would call this a minor bug because it seems possible and expected to traverse "in order" in this way.  Thanks for the report!

**Comment by luqui** [comment]
Oh and this [`weighted-search`](https://hackage.haskell.org/package/weighted-search) package.

**Comment by cdupont** [comment]
It's more clear, thanks!
